name: ohyo_jsonrpc2
version: 1.0.0

authors: 
- Dudochkin Victor <dudochkin.victor@gmail.com>
- Jim Washington <washington.jim@gmail.com>

description: JSON-RPC 2.0 pure transport agnostic implementation for Dart-2
homepage: https://github.com/ohyo-io/dart-jsonrpc2
environment:
  sdk: '>=2.0.0-dev.52.0 <2.0.0'

dependencies:
  logging:  ^0.11.0
  logging_handlers: ^0.8.0

dev_dependencies:
  build_runner: ^0.8.8
  build_web_compilers: ^0.4.0
  build_test: ^0.10.2

  http_server: any
  start: ^0.2.4
  test: ^0.12.0
  stream_channel: ^1.6.0
