name: ohyo-jsonrpc2
version: 1.0.0
author: Jim Washington <washington.jim@gmail.com>
description: JSON-RPC (v2.0) utilities for web applications.
homepage: https://github.com/jwashin/jsonrpc2-dart
environment:
  sdk: '>=2.0.0-dev.52.0 <2.0.0'

dependencies:
#  browser: ^0.10.0
  logging:  ^0.11.0
  logging_handlers: ^0.8.0

dev_dependencies:
  http_server: any
  start: ^0.2.4
  test: ^0.12.0
  stream_channel: ^1.6.0

dev_dependencies:
  build_runner: ^0.8.8
  build_web_compilers: ^0.4.0
  build_test: ^0.10.2
